### ISSUE TITLE
contributors

### ISSUE THREAD

**Issue by benmonro** [testing-library/eslint-plugin-jest-dom#1]
@allcontributors please add @benmonro for docs, code, examples, tests

**Comment by nickmccurdy** [comment]
It seems like you need to set up the bot manually: https://allcontributors.org/docs/en/bot/installation

**Comment by benmonro** [comment]
@nickmccurdy looks like only an org owner can add it.  @kentcdodds  can you add all contributors to this repo?

**Comment by kentcdodds** [comment]
@allcontributors please add @benmonro for docs, code, examples, tests

**Comment by kentcdodds** [comment]
It should ben enabled for all repos in the org

**Comment by benmonro** [comment]
@allcontributors please add @nickmccurdy  for code, docs and tests

**Comment by benmonro** [comment]
@allcontributors please add @gnapse for docs
