### ISSUE TITLE
expect.objectContaining support in toHaveStyle

### ISSUE THREAD

**Issue by benmonro** [testing-library/eslint-plugin-jest-dom#110]
- `eslint-plugin-jest-dom` version:
- `node` version:
- `npm` version:

Relevant code or config

```javascript
 expect(collapse.style).not.toContain(
    expect.objectContaining({
      display: 'none',
      height: '0px',
    })
  );

```

What you did:

What happened:
```

Error:
TypeError: Cannot read property 'replace' of undefined
Occurred while linting <text>:74
    at camelCase (/home/runner/work/eslint-plugin-jest-dom/eslint-plugin-jest-do
m/dist/rules/prefer-to-have-style.js:15:30)
    at Object.fix (/home/runner/work/eslint-plugin-jest-dom/eslint-plugin-jest-d
om/dist/rules/prefer-to-have-style.js:85:160)
```

Reproduction repository:
https://github.com/testing-library/eslint-plugin-jest-dom/runs/1470632531?check_suite_focus=true

Problem description:

Suggested solution:

**Comment by benmonro** [comment]
@AriPerkkio is it possible to configure the smoke test to only run against repositories that have `jest-dom` as a dependency?  It wouldn't make sense to run the smoke test against repos not using it.

**Comment by AriPerkkio** [comment]
Sure it's possible. I've generated a list of ~500 repositories which have `jest-dom` as dependency. I'll setup PR later. Heads up, there's a lot of crashes coming from `prefer-in-document` and some from `prefer-to-have-style`.

When looking for ESLint crashes it doesn't really matter whether your target repositories have `jest-dom` as dependency or not. The goal is to run these ESLint rules through as different AST as possible. As mentioned earlier, ESLint rules should not crash in any condition. 

But when running `eslint-remote-tester` in local environment (not CI) you might however want to run it against `jest-dom` dependent repositories. This is useful when you are checking whether changes in existing rules or new rules will flag false positives.
