### ISSUE TITLE
Consider setting the dependency to @testing-library/dom as a peerDependency

### ISSUE THREAD

**Issue by julienw** [testing-library/eslint-plugin-jest-dom#124]
I noticed that the dependency to `@testing-library/dom` is a "hard" dependency, I think this is used in https://github.com/testing-library/eslint-plugin-jest-dom/blob/7b6f5243674b17b287dbfd5df8ae16ea022aeb76/src/queries.js only.

The problem is that we may end up having different versions and copies of `@testing-library/dom` in a project, with this plugin using a more recent / older version than the one used in the tests. We may end up having a different list of queries, and the eslint plugin may have wrong results.

Therefore it could make sense that this dependency is a peer dependency. Indeed the users of this plugin who'll need this functionality will already have the dependency in their project anyway.

**Comment by benmonro** [comment]
Yeah I thought about that but to be honest that list hasn't changed in forever. Have you seen a specific problem related to this?

**Comment by julienw** [comment]
Mainly I was surprised that in my project I had the dependency to 2 different versions for the library. I use "yarn-deduplicate" so they both resolved to the same version for me, but I'm not sure this is the case for every users. Moreover this makes it necessary to bump this dependency regularly in this project as well, which can be a (small) burden. This is only a few kB but well...
