### ISSUE TITLE
Slip in `eslint --fix` rule for `jest-dom/prefer-to-have-style`

### ISSUE THREAD

**Issue by johan** [testing-library/eslint-plugin-jest-dom#175]
- `eslint-plugin-jest-dom` version: 3.8.1
- `node` version: v12.18.3
- `npm` version: 6.14.6

Relevant code or config

```javascript
expect(screen.getByRole("alert").getAttribute("inert")).toBe("");
```

What you did: I ran `eslint --fix`

What happened: It auto-corrected to the non-equivalent:

```js
expect(screen.getByRole("alert")).not.toHaveAttribute("inert");
```

Reproduction repository: Not available.

Problem description: The current behaviour is correct for values `null` and `undefined`; I'd expect there's a falsey-ness slip, somewhere. (Sadly I can't contribute a PR fix for legal reasons.)

Suggested solution: I expected it to auto-correct to the equivalent and working (in a DOM that has that empty attribute set):

```js
expect(screen.getByRole("alert")).toHaveAttribute("inert");
```

**Comment by mdotwills** [comment]
@johan I think this will fix your issue: https://github.com/testing-library/eslint-plugin-jest-dom/pull/180

**Comment by G-Rath** [comment]
@johan I think this is fixed - your code now gives `expect(screen.getByRole("alert")).toHaveAttribute("inert", "");` which looks correct to me.

Could you confirm if this is still an issue for you?

**Comment by johan** [comment]
Sweet, I see the same results as G-Rath with 4.0.1.
