### ISSUE TITLE
Update `@testing-library/dom` Dependency for the `v8` Release

### ISSUE THREAD

**Issue by jonioni** [testing-library/eslint-plugin-jest-dom#188]
- `eslint-plugin-jest-dom` version: v3.9.0
- `node` version: N/A
- `npm` version: N/A

Relevant code or config: `package.json`

```javascript
"dependencies": {
    ...
    "@testing-library/dom": "^7.28.1",
    ...
},
```

What you did: Install latest `@testing-library/dom@8.1.0`, `@testing-library/jest-dom@5.14.1`, and `eslint-plugin-jest-dom@3.9.0`.

What happened: https://github.com/testing-library/dom-testing-library/issues/963

```bash
TypeError: Cannot destructure property 'DOMElement' of '_prettyFormat.default.plugins' as it is undefined.
      ...
      at Object.<anonymous> (node_modules/@testing-library/dom/dist/pretty-dom.js:33:3)
      at Object.<anonymous> (node_modules/@testing-library/dom/dist/config.js:11:18)
      at Object.<anonymous> (node_modules/@testing-library/dom/dist/queries/label-text.js:8:15)
      at Object.<anonymous> (node_modules/@testing-library/dom/dist/queries/index.js:7:18)
      at Object.<anonymous> (node_modules/@testing-library/dom/dist/get-queries-for-element.js:8:46)
      at Object.<anonymous> (node_modules/@testing-library/dom/dist/index.js:61:29)
```

Problem description:

`@testing-library/dom@7.x.x` isn't compatible with the latest `@testing-library/dom@8.x.x` release.

Suggested solution:

```javascript
"dependencies": {
    ...
    "@testing-library/dom": "^7.28.1 || ^8.0.0",
    ...
},
```

Related: #185

**Comment by benmonro** [comment]
done

**Comment by G-Rath** [comment]
@benmonro I can't see where this is done? The dependency is still marked as requiring `^7.31.2` which doesn't allow v8; this is causing significant problems since I'm using `@testing-library/user-event` which has `@testing-library/dom` as a peer dependency that allows both v7 & v8 - the result is that `npm` is currently pulling in v7 of `@testing-library/dom` causing my tests to fail on v27 of `jest`.

**Comment by benmonro** [comment]
@G-Rath  sorry I'm not really able to provide  support any more.  I can give you admin if you want to provide a fix

**Comment by G-Rath** [comment]
@benmonro no problem - I'm happy to help with support :)

**Comment by benmonro** [comment]
Done. You are admin, thanks for the help @G-Rath
