### ISSUE TITLE
Support ESLint 8.x

### ISSUE THREAD

**Issue by MichaelDeBoey** [testing-library/eslint-plugin-jest-dom#190]
ESLint v8.0.0 is [released](https://eslint.org/blog/2021/10/eslint-v8.0.0-released) 🎉

It would be awesome to have official ESLint 8 support. 👊
I'm happy to help where I can of course 🙂

**Comment by benmonro** [comment]
Hi Michael would welcome a PR on this.

**Comment by weyert** [comment]
I think now with Node v10 support removed this PR can be merged?

**Comment by G-Rath** [comment]
We were already supporting eslint v8, but now we're testing against it in CI to ensure we remain compatible thanks to #237, so this is resolved 🎉

**Comment by G-Rath** [comment]
spoke too soon - #237 has our CI testing against multiple versions of ESLint, but doesn't include testing against v8 itself; that's handled by #200.

(We are still compatible with v8)
