### ISSUE TITLE
v3.9.1 does not include the compiled code

### ISSUE THREAD

**Issue by dardanos** [testing-library/eslint-plugin-jest-dom#194]
- `eslint-plugin-jest-dom` version: v3.9.1
- `node` version: 14.x
- `npm` version: 6.x

#### What you did:

Installed the last version of the library v3.9.1

#### What happened:

The library doesn't include the 

#### Reproduction repository:

v3.9.0 includes the file: https://unpkg.com/eslint-plugin-jest-dom@3.9.0/dist/index.js
v3.9.1 doesn't https://unpkg.com/eslint-plugin-jest-dom@3.9.1/dist/index.js

#### Suggested solution:

I think it's related to renaming `master` to `main` but I could be wrong.

**Comment by eps1lon** [comment]
Should be fixed in 3.9.2: https://unpkg.com/eslint-plugin-jest-dom@3.9.2/dist/index.js
