### ISSUE TITLE
Consider merging into eslint-plugin-testing-library

### ISSUE THREAD

**Issue by nickmccurdy** [testing-library/eslint-plugin-jest-dom#2]
Considering that `@testing-library/dom` and `@testing-library/react` have significantly more downloads on npm than `@testing-library/jest-dom`, I'd guess that most `jest-dom` users are already using one of the other `@testing-library` packages.

As a result, it may be helpful to merge efforts with the [`eslint-plugin-testing-library`](https://github.com/Belco90/eslint-plugin-testing-library) project, which is already listed in `testing-library`'s documentation and will hopefully be moved to the official GitHub organization soon (see https://github.com/Belco90/eslint-plugin-testing-library/issues/27). While not all users need both libraries, including both sets of rules shouldn't hurt as they only suggest improvements to using them, so users won't be told to use `testing-library` when using `jest-dom` and vice versa.

**Comment by benmonro** [comment]
@nickmccurdy yeah this actually started from that but for a number of reasons it made more sense to be decoupled from that plugin
