### ISSUE TITLE
Crashes when used with @typescript-eslint/parser

### ISSUE THREAD

**Issue by 10xjs** [testing-library/eslint-plugin-jest-dom#27]
Using this plugin in combination with `@typescript-eslint/parser` results in a crash with a `Fix objects must not be overlapped in a report.` error under certain conditions.

I have tracked the issue to the implementation of the `prefer-focus` rule and the use of apparently non-standard `.start` and `.end` fields.

This appears to be a solution to the same issue: https://github.com/jest-community/eslint-plugin-jest/pull/221.

**Comment by benmonro** [comment]
@10xjs would welcome a PR if you want to take a stab at it.

**Comment by zorfling** [comment]
@benmonro @10xjs - I just ran into this same issue so opened #30 to fix it based the eslint-plugin-jest PR above.

**Comment by benmonro** [comment]
Thanks so much for fixing this @zorfling, really appreciate it.
