### ISSUE TITLE
prefer-in-document: toHaveLength with no args causing crash and commas arent removed if multiple args were there

### ISSUE THREAD

**Issue by berkinanik** [testing-library/eslint-plugin-jest-dom#277]
- `eslint-plugin-jest-dom` version: 4.0.2
- `node` version: 16.17.0
- `npm` version: 8.19.0

Relevant code or config

test for following component will fail since jest matcher toHaveLength doesn't have its required expected:number parameter:

```javascript
export default function Home() {
  const items = [
    'item',
    'item1',
    'item3',
    'item2',
    'item4',
  ];

  return (
    <div className={styles.container}>
      <ul>
        {items.map((item, index) => (
          <li key={item}>
            {' '}
            {`${item}: #${index}`}
            {' '}
          </li>
        ))}
      </ul>
    </div>
  );
}
```

but eslint will crash because: prefer-in-document rules makes it crash while parsing the code. since no argument is in the matcherArguments, matcherArguments[0].value is .value on undefined

```javascript
describe('Home', () => {
  it('renders the list items', () => {
    render(<Home />);

    const list = screen.getByRole('list');

    expect(list).toBeInTheDocument();

    const listItems = screen.queryAllByRole('listitem');

    expect(listItems).toHaveLength();
  });
});
```

Also, following lines will be replaced by prefer-in-document falsely:

```javascript
const listItems = screen.queryAllByRole('listitem');
expect(listItems).toHaveLength(1, 2, 3);
```

fixed to:
```javascript
const listItems = screen.queryByRole('listitem');
expect(listItems).toBeInTheDocument(, , );
```

commas are still there.

What I did and Suggested solution:
Fix (#276)

Reproduction repository:
https://github.com/berkinanik/with-jest-app

**Comment by G-Rath** [comment]
Resolved by #276
