### ISSUE TITLE
Remove Semantic Pull Request from CI checks since its no longer maintained

### ISSUE THREAD

**Issue by G-Rath** [testing-library/eslint-plugin-jest-dom#278]
See https://github.com/zeke/semantic-pull-requests - since its no longer maintained PRs no longer get a green tick since the status never gets reported by that check; since this is an app I believe someone who has more permissions on the `testing-library` organisation has to action this.

@MichaelDeBoey I'm going to assign this to you to start since you're the main member of `testing-library` who I know 😄

**Comment by MatanBobi** [comment]
Thanks @G-Rath :)
I've uninstalled the app and since we don't have something like that in other repo's, I'm resolving this.

**Comment by G-Rath** [comment]
@MatanBobi it looks like this is still around?

See https://github.com/testing-library/eslint-plugin-jest-dom/pull/301

<img width="715" alt="image" src="https://github.com/testing-library/eslint-plugin-jest-dom/assets/3151613/acf88a25-1764-40b6-9f79-604a2d9b2b6c">

**Comment by MatanBobi** [comment]
Good catch @G-Rath, looks like I forgot to remove it from the branch protection rules :)
It's gone now:
![image](https://github.com/testing-library/eslint-plugin-jest-dom/assets/12711091/a238de65-78d3-41c5-8e1e-04033e926386)

Thanks!
