### ISSUE TITLE
Dependency on `@testing-library/dom`

### ISSUE THREAD

**Issue by eps1lon** [testing-library/eslint-plugin-jest-dom#294]
It's not apparent from the documentation why this plugin has a dependency on `@testing-library/dom`.

It looks like it does some branching based on whether a query is a DTL query or not but I can't find documentation how this affects rules in this repo.

This would help asses if we need a direct runtime dependency (current) or peer dependency or configuration option instead i.e. instead of requiring DTL and getting the list of queries, the user inputs that list. 

Documenting this internal behavior would help to understand if custom queries should also be considered.

Ideally there wouldn't be a dependency on /dom at all so that users just have to update /dom if that  releases a major and not update `/dom` and `eslint-plugin-jest-dom`. `jest-dom` doesn't have a dependency on `/dom` after all.

**Comment by ctjhoa** [comment]
Completely agree on that, I struggled to find why I have many `act` warning (https://github.com/testing-library/react-testing-library/issues/1051)  to finally see that there was a mismatch between `@testing-library/dom` required by `eslint-plugin-jest-dom` and `@testing-library/react`

**Comment by cbookg** [comment]
I had to remove this plugin in order to upgrade to React 18.  It would be nice to be able to add it back.

**Comment by ctjhoa** [comment]
@cbookg You can use [yarn resolutions](https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/) or [npm overrides](https://docs.npmjs.com/cli/v9/configuring-npm/package-json#overrides) to continue to use this plugin but not really a long term solution.
eg.
```
  "resolutions": {
    "@testing-library/dom": "^9.0.0",
  },
```
