### ISSUE TITLE
Wrong example for flat config in README

### ISSUE THREAD

**Issue by primeapple** [testing-library/eslint-plugin-jest-dom#379]
- `eslint-plugin-jest-dom` version: 5.4.0
- `node` version: 20.11.0
- `npm` version: 10.2.4

Relevant code or config

I have an ESlint flat configuration that uses ES Modules. This is the relevant code, :

```javascript
import pluginJestDom from "eslint-plugin-jest-dom";

export default [  
  ...pluginJs.configs.recommended,
];
```

When running this config I get: 
`TypeError: pluginJestDom.configs.flat/recommended is not iterable`

The fix you need is to remove the spreading operator and make it

```javascript
import pluginJestDom from "eslint-plugin-jest-dom";

export default [  
  pluginJs.configs.recommended,
];
```

You might want to change that in the README file :)
If the reason for this is ESModules, feel free to add this example to the README.

**Comment by G-Rath** [comment]
The readme is correct as it has you do a spread in an object whereas you're doing it in an array:

```
module.exports = [
  {
    files: [
      /* glob matching your test files */
    ],
    ...require("eslint-plugin-jest-dom").configs["flat/recommended"],
  },
];
```

The reason for this is that our rules expect to be running on test files so they're not suitable to enable for an entire codebase (which is what you're doing by including the config at the top-level) - so you want to merge our config with an object that defines `files`
