### ISSUE TITLE
Support ESLint 7.x

### ISSUE THREAD

**Issue by MichaelDeBoey** [testing-library/eslint-plugin-jest-dom#45]
ESLint v7.0.0 is [released](https://eslint.org/blog/2020/05/eslint-v7.0.0-released) 🎉

It would be awesome to have official ESLint 7 support. 👊
I'm happy to help where I can of course 🙂

**Comment by wKovacs64** [comment]
Out of curiosity, is there a reason this now *requires* ESLint v7 rather than just adds support for it in addition to v6?
