### ISSUE TITLE
prefer-checked fix is negating the resulting function when I believe it shouldn't be

### ISSUE THREAD

**Issue by joeycozza** [testing-library/eslint-plugin-jest-dom#49]
- `eslint-plugin-jest-dom` version: 2.1.0
- `node` version: 12.16.3
- `npm` version: 6.14.5

I have the following code
```javascript
  expect(SelectAll.getAttribute('aria-checked')).toEqual('true')
```
![Screen Shot 2020-05-21 at 2 16 47 PM](https://user-images.githubusercontent.com/3885959/82603926-b09dde80-9b70-11ea-941f-1e0d4b27a8cd.png)

The plugin wants to change it to 
```javascript
  expect(SelectAll).not.toBeChecked()
```

The value I'm expecting is 'true' as a string, and not a boolean. The --fix for this rule is changing it to .not.toBeChecked(), but I would expect one of the following.
1) `.toBeChecked()`
2) not --fix this instance since it is testing the attribute to be a specific string

It looks like this conditional located here could be updated to include the string 'true'. 
https://github.com/testing-library/eslint-plugin-jest-dom/blob/master/src/createBannedAttributeRule.js#L4

I'm not really familiar with dom APIs and aria-checked, so maybe checking against a string is an anti-pattern and I should just change my code somehow, I dunno.

Any guidance would be appreciated. I could make a PR adding the 'true' check to `getCorrectFunctionFor` function.

**Comment by benmonro** [comment]
Interesting.  I will look into those one thank you for reporting

**Comment by benmonro** [comment]
@joeycozza apologies u haven't had a chance to look into this. Any chance you could take a stab and open a PR?
