### ISSUE TITLE
Rule jest-dom/prefer-to-have-attribute autofix breaks the code

### ISSUE THREAD

**Issue by RIP21** [testing-library/eslint-plugin-jest-dom#52]
- `eslint-plugin-jest-dom` version: 3.0.1
- `node` version: 12.16.1
- `npm` version: 6.13.4

Turns this
```javascript
 expect(link.getAttribute('href')).toContain(`fincrime_analyst=${encodeURIComponent(mockedAnalyst.id)}`)
```
Into this
```javascript
expect(link).toHaveAttribute('href', expect.stringContaining(undefined))
```

**Comment by benmonro** [comment]
Yikes thanks for reporting. Mind opening a pull request?

**Comment by RIP21** [comment]
@benmonro I wish I have free time for that and familiarity with the codebase and ESLint instruments for AST stuff :) (I'm familiar with Babel mostly)
Anyway, will see, maybe I'll have motivation to do that :) 

Any resources you recommend to check out to get up to speed quickly?

**Comment by benmonro** [comment]
@RIP21 i personally like www.astexplorer.net as a playground.  In fact I do most of my work in that then move it into vscode from there.  Other than that the eslint docs are pretty good too.

**Comment by RIP21** [comment]
@benmonro sure, it's impossible to work with AST without it (the explorer) :D  
Okay, nothing new then. Babel documentation is a little meh and you really need to be stubborn to finally find something good about their AST instruments not just about plugins etc. that's why I'm asking :)

**Comment by benmonro** [comment]
Yeah.  What I like about eslint is the query syntax.  It's very similar to a css selector but for Dom nodes instead.  Anyway if I have time I'll comment on the issue that I'm working on it but it might be a few days as I'm on a family vacation at the moment
