### ISSUE TITLE
Rule jest-dom/prefer-empty - toBeEmpty is deprecated

### ISSUE THREAD

**Issue by ljosberinn** [testing-library/eslint-plugin-jest-dom#55]
- `eslint-plugin-jest-dom` version: 2.0.1
- `jest` version: 26.1.0
- `node` version: 13.9.0
- `npm` version: 6.13.7

Relevant code or config

What you did: Tried to use `expect(container.innerHTML).toBe('')` which got autofixed to `expect(container).toBeEmpty()`

What happened: Jest notes that this method has been deprecated.

![image](https://user-images.githubusercontent.com/29307652/86547052-e25be080-bf37-11ea-9d6e-31fdae2b5e4a.png)

Suggested solution: Migrate to `toBeEmptyDOMElement`. It's already noted here: https://github.com/testing-library/jest-dom#examples-1

**Comment by benmonro** [comment]
Oh nice thank you for reporting. Mind opening a PR for this?
