### ISSUE TITLE
new rule prefer-in-document

### ISSUE THREAD

**Issue by benmonro** [testing-library/eslint-plugin-jest-dom#75]
new rule that will auto fix `expect(screen.get|query|findAllBy()).toHaveLength(1)` into `expect(screen.get|query|findBy()).toBeInTheDocument()
Relevant code or config

**Comment by AntonNiklasson** [comment]
Hi there @benmonro 👋 I would like to give this a shot. Is it still relevant?

**Comment by benmonro** [comment]
Yes it is!  Would gladly welcome a Contribution for this @AntonNiklasson !

**Comment by AntonNiklasson** [comment]
Awesome! I'll give it a go during the weekend and update you on the progress.

**Comment by benmonro** [comment]
fixed in https://github.com/testing-library/eslint-plugin-jest-dom/pull/95
